language: go
go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

env:
  - GO15VENDOREXPERIMENT=1

script: 
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
